### ISSUE TITLE
Connect to iTunes Connect API with spaceship

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/flyve-mdm-ios-dashboard#12]
Hi, @ajsb85

I will change connect to iTunes Connect API from fastlane tools to spaceship
https://github.com/fastlane/fastlane/tree/master/spaceship

Regards.

**Comment by ajsb85** [comment]
Hi, @hectorerb 

I think, this issue is ready to close.
Could you confirm and close?

Thanks.

**Comment by hectorerb** [comment]
Hi, @ajsb85
We do not use Spaceship, we prefer to use fastlane and shell script for it. So yes, close you the issues

**Comment by ajsb85** [comment]
Spaceship already in use for the iOS projects.
