### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios-dashboard#26]
Hi, @Naylin15  
 
Could you split the code of conduct from the contributing guidelines? 
 
Thank you.

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done Pull Request #27

**Comment by ajsb85** [comment]
@Naylin15 Hi.
Please, read this documentation.
You can close issues from the commit or PR 👌🏻

https://help.github.com/articles/closing-issues-using-keywords/
