### ISSUE TITLE
Initial application settings

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/flyve-mdm-ios-dashboard#4]
- [x] define Bundle ID
- [x] add icon app
- [x] add splash app
- [x] build app with Travis CI
- [x] Integrate with fastlane

**Comment by ajsb85** [comment]
@hectorerb And the localizable file for Transifex. Dont forget for the boilerplate.

**Comment by rafaelje** [comment]
@ajsb85 the localizable files is going to be create in other issue because this don't have any text for now

Ref: https://github.com/flyve-mdm/flyve-mdm-ios-admin-dashboard/issues/6
