### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios-dashboard#8]
Hi, @hectorerb 

I will create gh-pages as requested in this issue: flyve-mdm/flyve-mdm.github.io#13

Best regards.

**Comment by ajsb85** [comment]
Hi, @hectorerb 
The project site is here at the moment: 
http://flyve.org/flyve-mdm-ios-admin-dashboard/
I will close this issue. 👍
